locales = [ "ach", "ar", "ast", "az", "bn", "bs", "ca", "cs", "da", "de", "dsb", "el", "en-AU", "en-CA", "en-GB", "en-IN", "en-NZ", "en-ZA", "es", "es-AR", "es-CL", "es-MX", "es-XL", "et", "fr", "fy-NL", "gu-IN", "he", "hi-IN", "hr", "hsb", "hu", "id", "it", "ja", "ka", "kab", "ko", "lg", "lo", "lv", "ml", "mr", "ms", "nb-NO", "nl", "nn-NO", "pa-IN", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sl", "sq", "sv-SE", "ta", "te", "th", "tr", "uk", "uz", "zh-CN", "zh-TW",]
[[paths]]
reference = "templates/pages/mozilla-donate.pot"
l10n = "locales/{locale}/pages/mozilla-donate.po"

[[paths]]
reference = "templates/pages/mozilla-donate/2020_mofo_annual-fund-general_global_all.pot"
l10n = "locales/{locale}/pages/mozilla-donate/2020_mofo_annual-fund-general_global_all.po"

[[paths]]
reference = "templates/pages/mozilla-donate/faq.pot"
l10n = "locales/{locale}/pages/mozilla-donate/faq.po"

[[paths]]
reference = "templates/pages/mozilla-donate/fighting-back.pot"
l10n = "locales/{locale}/pages/mozilla-donate/fighting-back.po"

[[paths]]
reference = "templates/pages/mozilla-donate/its-pi-day.pot"
l10n = "locales/{locale}/pages/mozilla-donate/its-pi-day.po"

[[paths]]
reference = "templates/pages/mozilla-donate/thunderbird.pot"
l10n = "locales/{locale}/pages/mozilla-donate/thunderbird.po"

[[paths]]
reference = "templates/pages/mozilla-donate/ways-to-give.pot"
l10n = "locales/{locale}/pages/mozilla-donate/ways-to-give.po"

